---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

workspace:
  path: /drone/src

steps:
  - name: test
    image: golang:1.18-alpine
    commands:
      - CGO_ENABLED=0 go test ./...
    when:
      exclude:
        event:
          - tag
          - promote

  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init
    when:
      event:
        - tag
        - promote

  - name: build
    image: golang:1.18-alpine
    commands:
      - apk add --no-cache make git gcc libc-dev
      - LDFLAGS="-static" make -C external/grafana build-go
    when:
      event:
        - tag
        - promote

  - name: archive
    image: alpine
    commands:
      - apk add --no-cache make
      - rm -f _gokrazy/extrafiles_arm64.tar
      - make _gokrazy/extrafiles_arm64.tar
    when:
      event:
        - tag
        - promote

  - name: push
    environment:
      GIT_SSH_COMMAND:
        from_secret: ssh_command
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOSTKEY:
        from_secret: ssh_hostkey
    image: alpine/git
    commands:
      - mkdir ~/.ssh
      - echo $${SSH_KEY} | base64 -d > ~/.ssh/id_ed25519
      - chmod 400 ~/.ssh/id_ed25519
      - echo $${SSH_HOSTKEY} >> ~/.ssh/known_hosts
      - chmod 600 ~/.ssh/known_hosts
      - git remote add ssh-origin $(echo ${DRONE_REMOTE_URL} | sed "s#https://#ssh://git@#")
      - git config user.email release@thatwebsite.xyz
      - git config user.name "Drone CI"
      - git add _gokrazy
      - git commit -m "[skip ci] extrafiles updated"
      - git pull --rebase --verbose ssh-origin ${DRONE_BRANCH}
      - git push --verbose ssh-origin ${DRONE_BRANCH}
    when:
      event:
        - tag
        - promote

---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: test
    image: golang:1.18-alpine
    commands:
      - CGO_ENABLED=0 go test ./...
    when:
      exclude:
        event:
          - tag
          - promote

  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init
    when:
      event:
        - tag
        - promote

  - name: build
    image: golang:1.18-alpine
    commands:
      - apk add --no-cache make git gcc libc-dev
      - LDFLAGS="-static" make -C external/grafana build-go
    when:
      event:
        - tag
        - promote

  - name: archive
    image: alpine
    commands:
      - apk add --no-cache make
      - rm -f _gokrazy/extrafiles_amd64.tar
      - make _gokrazy/extrafiles_amd64.tar
    when:
      event:
        - tag
        - promote

  - name: push
    environment:
      GIT_SSH_COMMAND:
        from_secret: ssh_command
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOSTKEY:
        from_secret: ssh_hostkey
    image: alpine/git
    commands:
      - mkdir ~/.ssh
      - echo $${SSH_KEY} | base64 -d > ~/.ssh/id_ed25519
      - chmod 400 ~/.ssh/id_ed25519
      - echo $${SSH_HOSTKEY} >> ~/.ssh/known_hosts
      - chmod 600 ~/.ssh/known_hosts
      - git remote add ssh-origin $(echo ${DRONE_REMOTE_URL} | sed "s#https://#ssh://git@#")
      - git config user.email release@thatwebsite.xyz
      - git config user.name "Drone CI"
      - git add _gokrazy
      - git commit -m "[skip ci] extrafiles updated"
      - git pull --rebase --verbose ssh-origin ${DRONE_BRANCH}
      - git push --verbose ssh-origin ${DRONE_BRANCH}
    when:
      event:
        - tag
        - promote
